var austinData =  [
	{
			"id": 1,
			"dateAdded": "04/01",
			"name": "Andiamo Ristorante",
			"phoneNumber": "(512) 719-3377",
			"streetAddress": "2521 Rutland Drive",
			"city": "Austin",
			"state": "TX",
			"zipCode": 78758,
            "county": null,
            "description": "The North Austin Italian restaurant is selling bulk fresh pasta for cooking at home.",
            "website": "https://andiamoitaliano.com/",
            "fullWebsite": "https://andiamoitaliano.com",
			"facebook": "null",
			"twitter": null,
			"source": ["https://www.statesman.com/entertainment/20200327/coronavirus-in-austin-restaurants-selling-groceries-to-customers"],
			"latlng": null,
			"hasMultipleLocations": false
        },{
			"id": 2,
			"dateAdded": "04/01",
			"name": "Bob's Steak & Chop House",
			"phoneNumber": "(512) 377-3474",
			"streetAddress": "301 Lavaca Street",
			"city": "Austin",
			"state": "TX",
			"zipCode": 78701,
            "county": null,
            "description": "The North Austin Italian restaurant is selling bulk fresh pasta for cooking at home.",
			"website": "bobs-steakandchop.com/austin/",
			"fullWebsite": "https://bobs-steakandchop.com/austin/",
			"facebook": "BobsSteakAndChopAustin",
			"twitter": null,
			"source": ["https://www.statesman.com/entertainment/20200327/coronavirus-in-austin-restaurants-selling-groceries-to-customers"],
			"latlng": null,
			"hasMultipleLocations": false
		},{
			"id": 3,
			"dateAdded": "04/01",
			"name": "Carve American Grille",
			"phoneNumber": "(512) 792-4450",
			"streetAddress": "7415 SW Parkway, Building 1",
			"city": "Austin",
			"state": "TX",
			"zipCode": 78735,
			"county": null,
			"description": "Perry’s sister restaurant is selling what it calls Hill Country Care Kits for $55, which include a slab of baby back ribs, Cornish game hen, corn, produce, tea and toilet paper; and a Breakfast Kit for $30 that includes a dozen eggs, a pound of bacon, hatch chile salsa, cheddar cheese, English muffins, tortillas, milk, produce and paper towels. Call 512-792-4450 for ordering the curbside service.",
			"website": "CarveAmericanGrill.com",
			"fullWebsite": "https://carveamericangrille.com",
			"facebook": "CARVEGrille",
			"twitter": null,
			"source": ["https://www.statesman.com/entertainment/20200327/coronavirus-in-austin-restaurants-selling-groceries-to-customers"],
			"latlng": null,
			"hasMultipleLocations": false
        },
        {
			"id": 4,
			"dateAdded": "04/01",
			"name": "Dai Due",
			"phoneNumber": "(512) 524–0688",
			"streetAddress": "2406 Manor Road, Suite A",
			"city": "Austin",
			"state": "TX",
			"zipCode": 78722,
			"county": null,
			"description": "In addition to its always excellent meat and condiments, the butcher shop and restaurant is selling produce bundles, along with essentials like eggs, bread, butter and milk.",
			"website": "daidue.com",
			"fullWebsite": "https://www.daidue.com/home",
			"facebook": "@daidue",
			"twitter": null,
			"source": ["https://www.statesman.com/entertainment/20200327/coronavirus-in-austin-restaurants-selling-groceries-to-customers"],
			"latlng": null,
			"hasMultipleLocations": false
		},{
			"id": 5,
			"dateAdded": "04/01",
			"name": "Foreign & Domestic",
			"phoneNumber": "(512) 459-1010",
			"streetAddress": "306 E 53rd Street",
			"city": "Austin",
			"state": "TX",
			"zipCode": 78751,
			"county": null,
			"description": "Chefs Sarah Heard and Nathan Lemley’s North Loop restaurant is selling produce, brioche loaves, sugar, egg, milk, cheese, yeat, flour and more. They are taking online ordering from 1 to 8 p.m. Tuesday-Saturday and 11 a.m. to 3 p.m. Sunday.",
			"website": "fndaustin.com",
			"fullWebsite": "http://fndaustin.com",
			"facebook": "FNDaustin",
			"twitter": null,
			"source": ["https://www.statesman.com/entertainment/20200327/coronavirus-in-austin-restaurants-selling-groceries-to-customers"],
			"latlng": null,
			"hasMultipleLocations": false
        },
        {
			"id": 6,
			"dateAdded": "04/01",
			"name": "Crema Bakery & Cafe",
			"phoneNumber": "(512) 282-1300",
			"streetAddress": "9001 Brodie Ln, Ste B3",
			"city": "Austin",
			"state": "TX",
			"zipCode": 78748,
			"county": null,
			"description": "The South Austin bakery and cafe is serving an array of produce, flour, bread, milk, eggs, rice sliced meat and more.",
			"website": "cremabakerycafe.com",
			"fullWebsite": "https://cremabakerycafe.com",
			"facebook": "CremaBakeryCafe",
			"twitter": null,
			"source": ["https://www.statesman.com/entertainment/20200327/coronavirus-in-austin-restaurants-selling-groceries-to-customers"],
			"latlng": null,
			"hasMultipleLocations": false
		},{
			"id": 7,
			"dateAdded": "04/01",
			"name": "Jester King Brewery & Kitchen",
			"phoneNumber": "(512) 661-8736",
			"streetAddress": "13187 Fitzhugh Road",
			"city": "Austin",
			"state": "TX",
			"zipCode": 78736,
			"county": null,
			"description": "In addition to their takeout, the restaurant is operating a drive-thru that sells all of the groceries needed to make cornbread (with a recipe), including buttermilk, cornmeal, eggs, flour, baking soda, salt and sugar.",
			"website": "jesterkingbrewery.com",
			"fullWebsite": "https://jesterkingbrewery.com",
			"facebook": "JesterKingBrewery",
			"twitter": null,
			"source": ["https://www.statesman.com/entertainment/20200327/coronavirus-in-austin-restaurants-selling-groceries-to-customers"],
			"latlng": null,
			"hasMultipleLocations": false
        },
        {
			"id": 8,
			"dateAdded": "04/01",
			"name": "LeRoy & Lewis",
			"phoneNumber": "(512) 945-9882",
			"streetAddress": "121 Pickle Road",
			"city": "Austin",
			"state": "TX",
			"zipCode": 78704,
			"county": null,
            "description": "The barbecue trailer is selling its regular menu of smoked meats, along with gallons of milk, butter, beef tallow, tortillas, ham and lard from Peaceful Pork and toilet paper.",
			"website": "leroyandlewis.com",
			"fullWebsite": "https://leroyandlewis.com/menu",
			"facebook": "@LeRoyandLewis",
			"twitter": null,
			"source": ["https://www.statesman.com/entertainment/20200327/coronavirus-in-austin-restaurants-selling-groceries-to-customers"],
			"latlng": null,
			"hasMultipleLocations": false
		},{
			"id": 9,
			"dateAdded": "04/01",
			"name": "Perry’s Steakhouse & Grille (Domain Northside-Austin)d",
			"phoneNumber": "(512) 270-6880",
			"streetAddress": "11801 Domain Blvd",
			"city": "Austin",
			"state": "TX",
			"zipCode": 78758,
			"county": null,
            "description": "Want to make your own steak dinner for two? The two Austin locations  of the steakhouse are selling grocery packs for $62, while supplies last. The packs include two 6-ounce filet mignons, two chicken breasts, potatoes, corn, broccoli, a gallon of milk and more. Many more packs available. Call Call (512) 270-6880 to check availability and reserve your packs.",
			"website": "perryssteakhouse.com",
			"fullWebsite": "https://perryssteakhouse.com/locations/tx/austin/domain-northside/",
			"facebook": "perrysdiningdomainnorthside",
			"twitter": null,
			"source": ["https://www.statesman.com/entertainment/20200327/coronavirus-in-austin-restaurants-selling-groceries-to-customers"],
			"latlng": null,
			"hasMultipleLocations": false
        },
        {
			"id": 10,
			"dateAdded": "04/01",
			"name": "Russian House of Austin",
			"phoneNumber": "(512) 428-5442",
			"streetAddress": "307 E 5th Street",
			"city": "Austin",
			"state": "TX",
			"zipCode": 78701,
			"county": null,
            "description": "The Russian restaurant and vodka bar is selling pasta, rice, eggs, milk, toilet paper and paper towels, according to an email from the restaurant.",
			"website": "russianhouseofaustin.com/",
			"fullWebsite": "https://russianhouseofaustin.com",
			"facebook": "RussianBistro",
			"twitter": null,
			"source": ["https://www.statesman.com/entertainment/20200327/coronavirus-in-austin-restaurants-selling-groceries-to-customers"],
			"latlng": null,
			"hasMultipleLocations": false
		},{
			"id": 11,
			"dateAdded": "04/01",
			"name": "Royal Fig Catering",
			"phoneNumber": "(512) 814-9743",
			"streetAddress": "2100 West Cannon Dr., Ste H",
			"city": "Austin",
			"state": "TX",
			"zipCode": 78745,
			"county": null,
            "description": "In addition to prepared meals, one of the city’s premier catering companies is selling steaks, ground beef, chicken, sausage, tortillas, muffins, juice, yogurt, eggs, produce and more, all of which can be purchased online for curbside pickup.",
			"website": "royalfig.com",
			"fullWebsite": "https://www.royalfig.com",
			"facebook": "RoyalFigCatering",
			"twitter": null,
			"source": ["https://www.statesman.com/entertainment/20200327/coronavirus-in-austin-restaurants-selling-groceries-to-customers"],
			"latlng": null,
			"hasMultipleLocations": false
        },
        {
			"id": 12,
			"dateAdded": "04/01",
			"name": "Salt & Time",
			"phoneNumber": "(512) 524-1383",
			"streetAddress": "1912 E. 7th Street",
			"city": "Austin",
			"state": "TX",
			"zipCode": 78702,
			"county": null,
			"description": "The butcher store is obviously selling all sorts of high-quality animal proteins, as well as Mill-king whole milk and half-and-half, farm eggs, cheese, Agua Dolce lettuce, organic produce from Johnson’s Backyard Garden, Fruitful Hill Farms produce and organic citrus from G&S Orchards.",
			"website": "saltandtimer.com",
			"fullWebsite": "http://www.saltandtime.com",
			"facebook": "saltandtime",
			"twitter": null,
			"source": ["https://www.statesman.com/entertainment/20200327/coronavirus-in-austin-restaurants-selling-groceries-to-customers"],
			"latlng": null,
			"hasMultipleLocations": false
		}
]
(edited)