var data =  [
		{
			"id": 2,
			"dateAdded": "03/28",
			"name": "Big Lou's Pizza",
			"phoneNumber": "(210) 337-0707",
			"streetAddress": "2048 S. WW White Rd.",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": "78222",
			"county": "Bexar",
			"description":  "Bodega stocked with meat, produce, bread, rice, beans, toilet paper and more. Limited to 50 a day. Call 210.337.0707",
			"website": "biglouspizza-satx.com",
			"facebook": "biglouspizza",
			"twitter": null,
			"source": ["https://www.facebook.com/biglouspizza/posts/3534962589907669","https://www.expressnews.com/food/restaurants/article/San-Antonio-restaurants-turn-into-grocery-stores-15152287.php"],
			"latlng": [28.5756184,-81.5332813]
		},
		{
			"id": 3,
			"dateAdded": "03/28",
			"name": "Cheesy Jane's",
			"phoneNumber": "(210) 826-0800",
			"streetAddress": "4200 Broadway St",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description":  "Dairy, eggs, meat, poultry, fruit, vegetables, toilet paper, laundry detergent and more",
			"website": "cheesyjanes.com",
			"facebook": "cheesyjanes",
			"twitter": null,
			"source": ["https://www.facebook.com/cheesyjanes/posts/2953872358002186, https://www.expressnews.com/food/restaurants/article/San-Antonio-restaurants-turn-into-grocery-stores-15152287.php"],
			"latlng": [29.465100, -98.463730]
		},
		{
			"id": 4,
			"dateAdded": "03/28",
			"name": "Cookhouse Restaurant",
			"phoneNumber": "(210) 320-8211",
			"streetAddress": "720 E Misteltoe Ave",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description":  "We are here for you SA! We've got your favorite Po'boys, classic Cookhouse dishes and meal + grocery kits all delivered to you curbside. Check out all of our offerings by visiting our website and learn more about our meal + grocery kits by...  ",
			"website": "cookhouseathome.com",
			"facebook": "cookhouserestaurant",
			"twitter": null,
			"source": ["https://www.facebook.com/cookhouserestaurant/posts/1344214172429110, https://www.expressnews.com/food/restaurants/article/San-Antonio-restaurants-turn-into-grocery-stores-15152287.php"],
			"latlng": [29.453090, -98.485210]
		},
		{
			"id": 5,
			"dateAdded": "03/28",
			"name": "Food Related",
			"phoneNumber": null,
			"streetAddress": "17401 Triton",
			"city": "Schertz",
			"state": "TX",
			"zipCode": 78154,
			"county": null,
			"description": "Food Related is now open for Curbside Order Pickup at our San Antonio Warehouse. No minimum orders or fees.",
			"website": "foodrelated.com",
			"facebook": "FoodRelatedFam",
			"twitter": null,
			"source": ["https://www.facebook.com/FoodRelatedFam/posts/3112994685380286","https://www.expressnews.com/food/restaurants/article/San-Antonio-restaurants-turn-into-grocery-stores-15152287.php"],
			"latlng": [29.599898,-98.280842]
		},
		{
			"id": 6,
			"dateAdded": "03/28",
			"name": "Frutería-Botanero",
			"phoneNumber": "(210) 251-3104",
			"streetAddress": "1401 S. Flores St",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description": "Toilet paper, fresh meat, beans, rice and other staples",
			"website": "thefruteria.com",
			"facebook": "thefruteriasa",
			"twitter": null,
			"source": ["https://www.expressnews.com/food/restaurants/article/San-Antonio-restaurants-turn-into-grocery-stores-15152287.php"],
			"latlng": [29.410070,-98.501820]
		},
		{
			"id": 7,
			"dateAdded": "03/28",
			"name": "Grayze",
			"phoneNumber": "(210) 481-8776",
			"streetAddress": "521 E. Grayson St",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description": "Need groceries? Grayze has you covered! Go to www.GrayzeOnGrayson.com and click Order Now. We have a limited supply, first come first served and we'll restock asap. 1 Gallon of Whole Milk, 15 eggs, 1lb butter, 1lb beans, 1lb rice, 1lb bacon, 1loaf of bread, 2small packs of coffee, 1pack of 72 sani wipes, 2rolls of Toilet Paper. Pick up for $35",
			"website": "grayzeongrayson.com",
			"facebook": "GrayzeOnGrayson",
			"twitter": null,
			"source": ["https://www.facebook.com/GrayzeOnGrayson/photos/a.1659647050970028/2544991235768934","https://www.expressnews.com/food/restaurants/article/San-Antonio-restaurants-turn-into-grocery-stores-15152287.php"],
			"latlng": [29.443390,-98.474660]
		},
		{
			"id": 8,
			"dateAdded": "03/28",
			"name": "J-Prime Steakhouse",
			"phoneNumber": "(210) 764-1604",
			"streetAddress": "1401 N. Loop 1604 W.",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description": "Selling packages of fresh produce for $20 as an add-on option to to-go orders with delivery via UberEats.",
			"website": "jprimesteakhouse.com",
			"facebook": null,
			"twitter": null,
			"source": ["https://www.expressnews.com/food/restaurants/article/San-Antonio-restaurants-turn-into-grocery-stores-15152287.php"],
			"latlng": [29.583780, -98.638440]
		},
		{
			"id": 9,
			"dateAdded": "03/28",
			"name": "Jason's Deli",
			"phoneNumber": null,
			"streetAddress": null,
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description": "Meat, cheese, fresh produce, eggs, bread and more.",
			"website": "jasonsdeli.com",
			"facebook": "JasonsDeli",
			"twitter": null,
			"source": ["https://www.expressnews.com/food/restaurants/article/San-Antonio-restaurants-turn-into-grocery-stores-15152287.php"],
			"latlng": null
		},
		{
			"id": 21,
			"dateAdded": "03/28",
			"name": "Jet-Setter",
			"phoneNumber": "(210) 272-0457",
			"streetAddress": "229 E. Houston St",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description": "Eggs, milk, fresh produce, pasta and more",
			"website": "jet-settersa.com",
			"facebook": "jetsettersa",
			"twitter": null,
			"source": ["https://www.expressnews.com/food/restaurants/article/San-Antonio-restaurants-turn-into-grocery-stores-15152287.php"],
			"latlng": [29.426782, -98.490137]
		},
		{
			"id": 10,
			"dateAdded": "03/28",
			"name": "La Gloria",
			"phoneNumber": "(210) 272-0457",
			"streetAddress": "100 E. Grayson St.",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description": "Toilet paper, fresh meat, beans, rice and other staples 12-5 p.m. PLEASE remember to stand 6ft apart if you are in line. Only credit/debit card payments will be accepted.",
			"website": "lagloria.com",
			"facebook": "lagloriapearl",
			"twitter": null,
			"source": ["https://www.facebook.com/lagloriapearl/posts/3138402252876693","https://www.expressnews.com/food/restaurants/article/San-Antonio-restaurants-turn-into-grocery-stores-15152287.php"],
			"latlng": [29.444245, -98.481233]
		},
		{
			"id": 11,
			"dateAdded": "03/28",
			"name": "La Panadería",
			"phoneNumber": "(210) 592-6264",
			"streetAddress": "301 E. Houston St",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description": "This “Support Locals Basket” directly helps support our staff. For $25 it includes: 1 loaf of Sourdough Bread, 1 piece of Pan Dulce Concha, 30 eggs, 2 lbs black beans, and 1 gallon of milk. ",
			"website": "lapanaderia.com",
			"facebook": "lapanaderia",
			"twitter": null,
			"source": ["https://www.facebook.com/lapanaderia/photos/a.404339402961722/3024066530988983/?type=3","https://www.expressnews.com/food/restaurants/article/San-Antonio-restaurants-turn-into-grocery-stores-15152287.php"],
			"latlng": [29.426618, -98.489567]
		},
		{
			"id": 12,
			"dateAdded": "03/28",
			"name": "Larder",
			"phoneNumber": "(210) 448-8355",
			"streetAddress": "136 E. Grayson St",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description": "Dairy, eggs, produce, meat, breads, prepared foods, sauces and more available for pickup at the store or Hotel Emma valet. ",
			"website": "larderatemma.com",
			"facebook": "LarderAtEmma",
			"twitter": null,
			"source": ["https://www.larderatemma.com/","https://www.expressnews.com/food/restaurants/article/San-Antonio-restaurants-turn-into-grocery-stores-15152287.php"],
			"latlng": [29.442822, -98.480901]
		},
		{
			"id": 13,
			"dateAdded": "03/28",
			"name": "Mi Tierra",
			"phoneNumber": "(210) 225-1262",
			"streetAddress": "218 Produce Row",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description": "Eggs, beans, bottled water, toilet paper, prepared food from its kitchen and more 10 a.m.-6 p.m. daily. ",
			"website": "mitierracafe.com",
			"facebook": null,
			"twitter": null,
			"source": ["https://www.expressnews.com/food/restaurants/article/San-Antonio-restaurants-turn-into-grocery-stores-15152287.php"],
			"latlng": [29.425037, -98.499715]
		},
		{
			"id": 14,
			"dateAdded": "03/28",
			"name": "Picnikins Cafe & Catering",
			"phoneNumber": null,
			"streetAddress": null,
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description": "Allow us to deliver fresh produce, breads, eggs, deli meats, fresh meats. cheeses and some of our signature prepared items.",
			"website": "picnikins.com",
			"facebook": "PicnikinsPatioCafe",
			"twitter": null,
			"source": ["https://www.restaurantcateringsystems.com/picnikinscatering/?form=home","https://www.expressnews.com/food/restaurants/article/San-Antonio-restaurants-turn-into-grocery-stores-15152287.php"],
			"latlng": null
		},
		{
			"id": 15,
			"dateAdded": "03/28",
			"name": "The Rustic",
			"phoneNumber": "(210) 245-7500",
			"streetAddress": "17619 La Cantera Parkway, Suite 204",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description": "Menu packages of fresh meats, poultry and seafood along with a bag of vegetables, fruit and butter for $65 available for takeout when ordered by phone 11 a.m.-8 p.m. daily.",
			"website": "therustic.com",
			"facebook": "therusticsa",
			"twitter": null,
			"source": ["https://www.expressnews.com/food/restaurants/article/San-Antonio-restaurants-turn-into-grocery-stores-15152287.php"],
			"latlng": [29.610231, -98.598609]
		},
		{
			"id": 16,
			"dateAdded": "03/28",
			"name": "Saltgrass Steak House",
			"phoneNumber": null,
			"streetAddress": null,
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description": "All locations are taking phone orders for cut steaks, seafood, poultry, dairy, produce and more for pickup. ",
			"website": "saltgrass.com",
			"facebook": null,
			"twitter": null,
			"source": ["https://www.expressnews.com/food/restaurants/article/San-Antonio-restaurants-turn-into-grocery-stores-15152287.php"],
			"latlng": null
		},
		{
			"id": 17,
			"dateAdded": "03/28",
			"name": "Sangria on the Burg",
			"phoneNumber": "(210) 265-3763",
			"streetAddress": "5115 Fredericksburg Road",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description": "Quarantine Packages Available. To order please call 210-265-3763. The lines will be busy. Please keep trying... Thanks!!! $25 - 1 gallon milk, 15 eggs, 5lbs beans, 5lbs rice, 4 rolls TP",
			"website": "sangriaontheburg.com",
			"facebook": "sangriaontheburg",
			"twitter": null,
			"source": ["https://www.facebook.com/sangriaontheburg/posts/3529342867140585","https://www.expressnews.com/food/restaurants/article/San-Antonio-restaurants-turn-into-grocery-stores-15152287.php"],

			"latlng": [29.501578, -98.559825]
		},
		{
			"id": 18,
			"dateAdded": "03/28",
			"name": "Still Golden Social House",
			"phoneNumber": "(210) 616-2212",
			"streetAddress": "1900 Broadway",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description": "Orders of rice, beans, meat, produce and more available for free pickup of $4 delivery in a 5-mine radius. Also delivering beer, wine and cocktail kits. Email orders to StillHoldenSocialHouse@gmail.com. TXT orders to 210-802-5724.",
			"website": "stillgoldensa.com",
			"facebook": "StillGoldenSH",
			"twitter": null,
			"source": ["https://www.facebook.com/StillGoldenSH/posts/2761922120591866","https://www.expressnews.com/food/restaurants/article/San-Antonio-restaurants-turn-into-grocery-stores-15152287.php"],
			"latlng": [29.443622, -98.476223]
		},
		{
			"id": 19,
			"dateAdded": "03/28",
			"name": "Whiskey Cake",
			"phoneNumber": "(210) 236-8095",
			"streetAddress": "15900 La Cantera Parkway",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description": " 'Survival kits' of beef, chicken, dairy products, fresh vegetables, eggs and more that changes daily. Check Facebook: @WhiskeyCakeSa for daily kit details. Pickup from car in line that forms at 11 a.m.",
			"website": "whiskeycake.com",
			"facebook": "WhiskeyCakeSa",
			"twitter": null,
			"source": ["https://www.expressnews.com/food/restaurants/article/San-Antonio-restaurants-turn-into-grocery-stores-15152287.php"],
			"latlng": [29.593067, -98.615641]
		},
		{
			"id": 20,
			"dateAdded": "03/28",
			"name": "The Winchester",
			"phoneNumber": "(210) 721-7762",
			"streetAddress": "5148 Broadway St.",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description": "Selling grocery packages with meat, dairy, eggs, produce for $55 with optional add-on items. Exact items updated daily at Facebook: @thewinchester78209.",
			"website": "thewinchestersanantonio.com",
			"facebook": "thewinchester78209",
			"twitter": null,
			"source": ["https://www.expressnews.com/food/restaurants/article/San-Antonio-restaurants-turn-into-grocery-stores-15152287.php"],
			"latlng": [29.474298, -98.462291]
		},
		{
			"id": 21,
			"dateAdded": "03/28",
			"name": "The People's Nite Market @ The Dakota San Antonio",
			"phoneNumber": null,
			"streetAddress": "433 S Hackberry",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": 78203,
			"county": "Bexar",
			"description": "Hello Nite People! We have teamed up with several community organizations(@eastsidemarketsa , @garciastreetfarm and The Dakota Ice House) to provide some basic staples that are very much needed at the moment. April 1st, from 3pm-9pm at @thedakotasa on S. Hackberry we will be providing a Community Curbside Market pick-up for pre-ordered veggie packs from @rivercityproduce and have a limited amount of staples folks are having issues finding at local grocery stores. \n Staples Include: Beans, Rice, Bread(white/wheat) Eggs(dozen), local honey from @nectardfleur , veggie garden starts from @sano_nursery (Prices are subject to change based on demand at the moment)",
			"website": null,
			"facebook": "thepeoplesnitemarket",
			"twitter": null,
			"source": ["https://www.facebook.com/thepeoplesnitemarket/posts/2318467941786922"],
			"latlng": [29.416120, -98.473440]
		},
		{
			"id": 21,
			"dateAdded": "03/28",
			"name": "Theory Coffee Co",
			"phoneNumber": null,
			"streetAddress": "2437 Nacogdoches Rd",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": 78209,
			"county": "Bexar",
			"description": "Mill-King 1% Milk - $6.50 - Expiration 4/8 ",
			"website": "theorycoffeeco.com/shop",
			"facebook": null,
			"twitter": null,
			"source": ["https://www.theorycoffeeco.com/shop"],
			"latlng": [29.508492, -98.457497]
		},
		{
			"id": 22,
			"dateAdded": "03/28",
			"name": "Fralo's Pizza",
			"phoneNumber": "(210) 698-6616",
			"streetAddress": "23651 W Interstate 10",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": 78257,
			"county": "Bexar",
			"description": "Eggs, fruit, vegetables, and more.",
			"website": "fralos.com",
			"facebook": "fralospizza",
			"twitter": null,
			"source": ["https://www.sanantoniomag.com/restaurants-help-provide-pantry-staples-during-coronavirus/"],
			"latlng": [29.661260, -98.627959]
		},
		{
			"id": 23,
			"dateAdded": "03/28",
			"name": "Nicha’s Comida Mexicana",
			"phoneNumber": "(210) 922-3330",
			"streetAddress": null,
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description": "Groceries are ready! Avoid the long lines and come by any of our Nicha’s locations to pick up what you need! Here’s what we have: Bleach, Toilet paper, Eggs, Liquid eggs, Sugar, White bread, Tortillas, Lasagna trays, potatoes, loose and canned beans and beans, Flour, Bottled water packs and Gloves. There’s more to come! We will keep you guys updated.",
			"website": "nichas.com",
			"facebook": "nichascomidamexicana",
			"twitter": null,
			"source": ["https://www.facebook.com/nichascomidamexicana/posts/3449182845098819"],
			"latlng": [29.661260, -98.627959],
			"hasMultipleLocations": true,
			"locations":[
				{
					"phoneNumber": "(210) 680-4420",
					"streetAddress": "5059 Northwest Loop 410",
					"city": "San Antonio",
					"state": "TX",
					"zipCode": 78229,
					"latlng": null
				},
				{
					"phoneNumber": "(210) 922-3330",
					"streetAddress": "3119 Roosevelt Avenue",
					"city": "San Antonio",
					"state": "TX",
					"zipCode": 78214,
					"latlng": null
				},
				{
					"phoneNumber": "(210) 655-4420",
					"streetAddress": "7929 Pat Booker Road",
					"city": "San Antonio",
					"state": "TX",
					"zipCode": 78233,
					"latlng": null
				}
			]
		},
		{
			"id": 24,
			"dateAdded": "03/28",
			"name": "Halcyon Southtown",
			"phoneNumber": "(210) 277-7045",
			"streetAddress": "1414 S Alamo St",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": 78210,
			"county": "Bexar",
			"description": "Southtown residents and friends of Halcyon - If you need groceries, family meals, coffee, or even alcohol, Halcyon has you covered! ONLINE ORDERING FORM.",
			"website": "halcyoncoffeebar.com",
			"facebook": "HalcyonSouthtown",
			"twitter": null,
			"source": ["https://www.facebook.com/HalcyonSouthtown/posts/3088196057897849"],
			"latlng": [29.410001, -98.495465],
			"hasMultipleLocations": false,
		},
		{
			"id": 25,
			"dateAdded": "03/28",
			"name": "Hearthstone Bakery Cafe",
			"phoneNumber": "(210) 826-5668",
			"streetAddress": null,
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description": "Thank you for requesting an order form. Please call (210) 826-5668 between 10AM and 3 PM Monday through Friday to place your orders for next day pick up and delivery.",
			"website": "hearthstonebakerycafe.com",
			"facebook": "Hearthstone-Bakery-Cafe-128818360498502",
			"twitter": null,
			"source": ["https://www.facebook.com/permalink.php?story_fbid=2940957732617870&id=128818360498502"],
			"latlng": null,
			"hasMultipleLocations": true,
			"locations":[
				{
					"phoneNumber": null,
					"streetAddress": "4212 McCullough Ave",
					"city": "San Antonio",
					"state": "TX",
					"zipCode": 78212,
					"latlng": [29.469557, -98.491378]
				},{
					"phoneNumber": null,
					"streetAddress": "3920 Harry Wurzbach Rd",
					"city": "San Antonio",
					"state": "TX",
					"zipCode": 78209,
					"latlng": [29.506185, -98.434082]
				}
			]
		},
		{
			"id": 26,
			"dateAdded": "03/29",
			"name": "Mako's on the Creek",
			"phoneNumber": "(830) 730-5947",
			"streetAddress": "169 Buffalo Pl",
			"city": "Cibolo",
			"state": "TX",
			"zipCode": 78108,
			"county": null,
			"description": " All-Purpose Flour (5 LB) - $3.00 Dozen Eggs (XL Grade AA) - $3.50 Loaf White Bread - $2.00 Loaf Wheat Bread - $2.50 Flour Tortillas (20 pack) - $2.50 Long Grain White Rice (5 LB) - $5.00 Unsalted Butter (1 LB) - $4.00 Spaghetti (1 LB) - $2.00 Chicken Breast (Skinless Boneless - by the LB) - $3.00 Ground Beef (by the LB) - $4.00 Sharp Cheddar (1.5 LB) - $6.00 Heavy Whipping Cream (QT) - $5.50 Idaho Potatoes (5 LB) - $5.00 Spring Mix (1 LB) - $4.50 Orange Juice (1/2 GAL) - $6.00 Apple Juice (6 pack of 12 oz) - $12.00 and more....",
			"website": "makostx.com",
			"facebook": "makosonthecreek",
			"twitter": null,
			"source": ["http://www.makostx.com/grocery"],
			"latlng": [29.557694, -98.242199],
			"hasMultipleLocations": false,
		},
		{
			"id": 27,
			"dateAdded": "03/29",
			"name": "Bill Miller BBQ",
			"phoneNumber": null,
			"streetAddress": null,
			"city": null,
			"state": "TX",
			"zipCode": null,
			"county": null,
			"description": "Roll on in to your local #BillMillerRoll of paper 12 rolls per person while supplies last, subject to change. 1/2 gallon whole milk - $3.00. Multiple Locations.",
			"website": "billmillerbbq.com",
			"facebook": "BillMillerBarBQ",
			"twitter": null,
			"source": ["https://twitter.com/BillMillerBarBQ/status/1243900807734534151"],
			"latlng": null,
			"hasMultipleLocations": false,
		},
		{
			"id": 28,
			"dateAdded": "03/29",
			"name": "Texas Roadhouse",
			"phoneNumber": null,
			"streetAddress": null,
			"city": null,
			"state": "TX",
			"zipCode": null,
			"county": null,
			"description": "Texas Roadhouse is offering a variety of steaks, including ribeye, strips, sirloin and filet. Guests are encouraged to call the restaurant to place an order.",
			"website": "texasroadhouse.com",
			"facebook": "texasroadhouse",
			"twitter": null,
			"source": ["https://www.ksat.com/news/local/2020/03/28/texas-roadhouse-restaurants-selling-ready-to-grill-steaks/"],
			"latlng": null,
			"hasMultipleLocations": true,
		},
		{
			"id": 29,
			"dateAdded": "03/29",
			"name": "Cured at Pearl",
			"phoneNumber": "(210) 314-3929",
			"streetAddress": "306 Pearl Pkwy",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": 78215,
			"county": "Bexar",
			"description": "Sometimes it’s just about the eggs and toilet paper. Come get your sundries at Cured! @ Cured at Pearl",
			"website": "curedatpearl.com",
			"facebook": "curedatpearl",
			"twitter": null,
			"source": ["https://www.facebook.com/curedatpearl/posts/1336087859915916", "https://therivardreport.com/these-locally-owned-eateries-offer-takeout-delivery-services"],
			"latlng": [29.441942, -98.479010],
			"hasMultipleLocations": false,
		},
		{
			"id": 30,
			"dateAdded": "03/29",
			"name": "Restaurant Gwendolyn",
			"phoneNumber": "(210) 222-1849",
			"streetAddress": "152 E Pecan St, Ste 100",
			"city": "San Antonio",
			"state": "TX",
			"zipCode": 78205,
			"county": "Bexar",
			"description": "NEW GROCERY ITEMS! Today's additions include butter, toilet paper, milk, and more. Call 210-222-1849 or text 210-887-7512 to place your curbside order!",
			"website": "restaurantgwendolyn.com",
			"facebook": "RestaurantGwendolyn",
			"twitter": null,
			"source": ["https://www.facebook.com/RestaurantGwendolyn/posts/2858961304184116", "https://therivardreport.com/these-locally-owned-eateries-offer-takeout-delivery-services"],
			"latlng": [29.428513, -98.491557],
			"hasMultipleLocations": false,
		},
		{
			"id": 31,
			"dateAdded": "03/30",
			"name": "Stone Werks",
			"phoneNumber": null,
			"streetAddress": null,
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description": "Curbside and Pick Up only. FIRST COME FIRST SERVE. Kit Includes: 2lb of Ground Beef, 2lb of Chicken Breast, Select Produce, 2 Bottles of Wine (.75 l), 2 Rolls of Toilet Paper, 15 Eggs,Gallon of Milk, 1 Loaf of Bread, 1lb of Butter $50. Magnum Bottles: Cabernet, Sangria, Chardonnay, $20 each. Multiple Locations.",
			"website": "stonewerks.com",
			"facebook": "StoneWerks",
			"twitter": null,
			"source": ["https://www.facebook.com/StoneWerks/posts/10158054397604471"],
			"latlng": null,
			"hasMultipleLocations": true
		},
		{
			"id": 32,
			"dateAdded": "03/30",
			"name": "Brothers Produce",
			"phoneNumber": null,
			"streetAddress": null,
			"city": "San Antonio",
			"state": "TX",
			"zipCode": null,
			"county": "Bexar",
			"description": "NEW DROP-OFF SITES FOR THE REST OF THIS WEEK!! All you need to do is show up during the location time and we will have the pre-made fruit and veg boxes ready for you! CASH ONLY for these sites. We will stay at the site until the time ends or until we run out of product. Boxes are $20 each! Multiple Locations in Austin and San Antonio (Thursday 4/2). Check facebook for details.",
			"website": "brothersproducedallas-austin.com",
			"facebook": "BrothersProduce.Austin",
			"twitter": null,
			"source": ["https://www.facebook.com/BrothersProduce.Austin/posts/3137917682927493"],
			"latlng": null,
			"hasMultipleLocations": true
		}
	]


